site_name: 'example-docs'

repo_url: https://github.com/bchen528/backstage-test/
edit_uri: 'edit/main/docs/'

nav:
#   - Home: 'index.md'
#   - README: '../'
#   - Google: 'https://google.com/'
#   - More docs: 'more_docs/**/*.md'
#   - Playbooks: '!include ./playbooks/mkdocs.yml'

# plugins:
#   - monorepo

